#!/bin/bash
#
# 30_gen_ssl_keys.sh
#

KEY_DIR="/config/keys"
CRT="${KEY_DIR}/cert.crt"
KEY="${KEY_DIR}/cert.key"
SERVER_FILE="${KEY_DIR}/ServerName"
CNF="${KEY_DIR}/openssl-selfsigned.cnf"

APACHE_SERVERNAME_CONF="/etc/apache2/conf-enabled/00-servername.conf"

# Self-signed policy.
DAYS_VALID=825
RENEW_WITHIN_DAYS=30

# Marker so we only auto-rotate our own autogenerated certs.
AUTOGEN_O="Self-Signed"
AUTOGEN_OU="AUTOGEN"

rc=0
need_gen=0
reason=""
SERVER=""

log_msg()
{
	local msg="$1"
	echo "[ssl] ${msg}"
}

cert_expires_within_days()
{
	local days="$1"
	local seconds=0

	seconds=$((days * 86400))

	# Returns 0 if cert is valid for at least "seconds" from now; non-zero otherwise.
	openssl x509 -in "${CRT}" -noout -checkend "${seconds}" >/dev/null 2>&1
	return $?
}

is_our_cert()
{
	local subj=""
	local iss=""
	local san=""

	# Subject marker check.
	subj="$(openssl x509 -in "${CRT}" -noout -subject 2>/dev/null)"
	if ! echo "${subj}" | grep -q "O=${AUTOGEN_O}" || ! echo "${subj}" | grep -q "OU=${AUTOGEN_OU}"; then
		return 1
	fi

	# Must be self-signed: issuer == subject.
	iss="$(openssl x509 -in "${CRT}" -noout -issuer 2>/dev/null)"
	if [[ -z "${iss}" || "${iss}" != "${subj/subject=/issuer=}" ]]; then
		return 1
	fi

	# Must include our generic SAN baseline.
	san="$(openssl x509 -in "${CRT}" -noout -ext subjectAltName 2>/dev/null)"
	if ! echo "${san}" | grep -q "DNS:localhost" || ! echo "${san}" | grep -q "IP Address:127.0.0.1"; then
		return 1
	fi

	return 0
}

ensure_servername()
{
	if [[ ! -s "${SERVER_FILE}" ]]; then
		echo "localhost" > "${SERVER_FILE}"
	fi

	SERVER="$(cat "${SERVER_FILE}" 2>/dev/null)"
	if [[ -z "${SERVER}" ]]; then
		SERVER="localhost"
		echo "${SERVER}" > "${SERVER_FILE}"
	fi

	return 0
}

write_apache_servername_conf()
{
	# Write a real Apache directive snippet. apache2.conf already includes conf-enabled/*.conf.
	echo "ServerName ${SERVER}" > "${APACHE_SERVERNAME_CONF}"

	chown root:root "${APACHE_SERVERNAME_CONF}" >/dev/null 2>&1
	chmod 644 "${APACHE_SERVERNAME_CONF}" >/dev/null 2>&1

	return 0
}

ensure_selfsigned_cnf()
{
	if [[ -s "${CNF}" ]]; then
		return 0
	fi

	cat > "${CNF}" <<EOF
[req]
distinguished_name = dn
x509_extensions = v3_req
prompt = no

[dn]
C = US
ST = NA
L = NA
O = ${AUTOGEN_O}
OU = ${AUTOGEN_OU}
CN = ${SERVER}

[v3_req]
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = ${SERVER}
DNS.2 = localhost
IP.1 = 127.0.0.1
EOF

	return 0
}

generate_cert()
{
	ensure_selfsigned_cnf

	openssl req -x509 -nodes -days "${DAYS_VALID}" -newkey rsa:2048 \
		-keyout "${KEY}" \
		-out "${CRT}" \
		-config "${CNF}" \
		>/dev/null 2>&1

	# Basic sanity checks.
	openssl x509 -in "${CRT}" -noout >/dev/null 2>&1
	if [[ $? -ne 0 ]]; then
		return 1
	fi

	openssl rsa -in "${KEY}" -noout -check >/dev/null 2>&1
	if [[ $? -ne 0 ]]; then
		return 1
	fi

	return 0
}

# Ensure key directory exists.
mkdir -p "${KEY_DIR}" >/dev/null 2>&1

# Ensure ServerName exists and is non-empty (value file).
ensure_servername

# Write Apache global ServerName directive from the value file.
write_apache_servername_conf

# Decide if we need to generate/renew. Use -s to reject zero-byte files.
if [[ -s "${KEY}" && -s "${CRT}" ]]; then
	is_our_cert
	if [[ $? -eq 0 ]]; then
		# Our autogenerated cert ? rotate if expired or near expiry.
		cert_expires_within_days "${RENEW_WITHIN_DAYS}"
		if [[ $? -ne 0 ]]; then
			need_gen=1
			reason="(autogen cert expiring/expired)"
		fi
	else
		# User-provided cert ? do not modify, but warn if expired.
		cert_expires_within_days 0
		if [[ $? -ne 0 ]]; then
			log_msg "WARNING: TLS certificate in ${KEY_DIR} is expired. Please replace it."
		fi
	fi
else
	# New install or broken/partial files.
	need_gen=1
	reason="(missing/empty cert/key)"
fi

if [[ ${need_gen} -eq 1 ]]; then
	log_msg "Generating self-signed keys in ${KEY_DIR} ${reason} (CN=${SERVER} with SAN). You can replace these with your own keys if required."

	# Remove any partial outputs first.
	rm -f "${CRT}" "${KEY}" >/dev/null 2>&1

	generate_cert
	if [[ $? -ne 0 ]]; then
		log_msg "ERROR: Failed to generate self-signed certificate in ${KEY_DIR}"
		rc=1
	fi
else
	log_msg "Using existing keys in \"${KEY_DIR}\""
fi

# Permissions.
chown root:root "${KEY_DIR}" >/dev/null 2>&1
chmod 755 "${KEY_DIR}" >/dev/null 2>&1

chown root:root "${CRT}" >/dev/null 2>&1
chmod 600 "${CRT}" >/dev/null 2>&1

chown root:root "${KEY}" >/dev/null 2>&1
chmod 600 "${KEY}" >/dev/null 2>&1

chown root:root "${SERVER_FILE}" >/dev/null 2>&1
chmod 644 "${SERVER_FILE}" >/dev/null 2>&1

exit ${rc}
