name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: phusion/baseimage
    environment: playground
    permissions:
     contents: read
     packages: write
    steps:
    # Checkout repository
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
       registry: ${{ env.REGISTRY }}
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Check variables
      run: |
        echo 'Current path:'
        pwd
        echo 'Tag: ${{ steps.meta.outputs.tags }}'
        echo 'Label: ${{ steps.meta.labels.tags }}'
