name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Run tests with coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Test coverage $COVERAGE% is below the set threshold of 80%"
            exit 1
          fi
          echo "✅ Test coverage: $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
